In [ ]:
# import array_to_latex as a2l 
# import numpy as np

In [27]:
from sympy import symbols, Matrix, sqrt, Rational, latex, evaluate, N
from sympy import Max

In [64]:
# Input features
X = Matrix([[1], [1], [1], [1]])
# First layer
W_0 = Matrix([[Rational(1, 2), -Rational(2, 10)]])


# Star graph $S^{4}$

In [35]:
# Define the variable u
u = 1/sqrt(2)

A = Rational(1, 2) * Matrix([
    [Rational(1, 2), u, u, u],
    [u, 1, 0, 0],
    [u, 0, 1, 0],
    [u, 0, 0, 1]
])
Z_0_before_relu = A*X*W_0
Z_0 = Z_0_before_relu.applyfunc(lambda x: Max(0, x))
Z_0


Matrix([
[1/8 + 3*sqrt(2)/8, 0],
[  sqrt(2)/8 + 1/4, 0],
[  sqrt(2)/8 + 1/4, 0],
[  sqrt(2)/8 + 1/4, 0]])

In [34]:
W_1 = Matrix([
    [Rational(3,10), -Rational(2,5), Rational(4,5), Rational(1,2)],
    [-1.1, 0.6, -0.1, 0.7]
])
Z_1 = (A*Z_0*W_1).applyfunc(lambda x: Max(0, x))
Z_1

Matrix([
[ 3/320 + 9*sqrt(2)/320 + 9*sqrt(2)*(sqrt(2)/8 + 1/4)/40, 0, 1/40 + 3*sqrt(2)/40 + 3*sqrt(2)*(sqrt(2)/8 + 1/4)/5, 1/64 + 3*sqrt(2)/64 + 3*sqrt(2)*(sqrt(2)/8 + 1/4)/8],
[3*sqrt(2)/160 + 3/80 + 3*sqrt(2)*(1/8 + 3*sqrt(2)/8)/40, 0,   sqrt(2)/20 + 1/10 + sqrt(2)*(1/8 + 3*sqrt(2)/8)/5,   sqrt(2)/32 + 1/16 + sqrt(2)*(1/8 + 3*sqrt(2)/8)/8],
[3*sqrt(2)/160 + 3/80 + 3*sqrt(2)*(1/8 + 3*sqrt(2)/8)/40, 0,   sqrt(2)/20 + 1/10 + sqrt(2)*(1/8 + 3*sqrt(2)/8)/5,   sqrt(2)/32 + 1/16 + sqrt(2)*(1/8 + 3*sqrt(2)/8)/8],
[3*sqrt(2)/160 + 3/80 + 3*sqrt(2)*(1/8 + 3*sqrt(2)/8)/40, 0,   sqrt(2)/20 + 1/10 + sqrt(2)*(1/8 + 3*sqrt(2)/8)/5,   sqrt(2)/32 + 1/16 + sqrt(2)*(1/8 + 3*sqrt(2)/8)/8]])

In [47]:
from utils import normalize_adjacency
import networkx as nx
import numpy as np
G = nx.star_graph(3)
Anorm = normalize_adjacency(nx.adjacency_matrix(G))
X = np.ones((4, 1))
W0 = np.array([[0.5, -0.2]])
W1 = np.array([[0.3, -0.4, 0.8, 0.5], [-1.1, 0.6, -0.1, 0.7]])
Z0 = (Anorm@X@W0).clip(0, None)
Z1 = (Anorm@Z0@W1).clip(0, None)
print(f"{Z0} \n{np.array(N(Z_0))}")
print(f"{Z1} \n{np.array(N(Z_1))}")


[[0.65533009 0.        ]
 [0.4267767  0.        ]
 [0.4267767  0.        ]
 [0.4267767  0.        ]] 
[[0.655330085889911 0]
 [0.426776695296637 0]
 [0.426776695296637 0]
 [0.426776695296637 0]]
[[0.18494927 0.         0.49319805 0.30824878]
 [0.13352476 0.         0.35606602 0.22254126]
 [0.13352476 0.         0.35606602 0.22254126]
 [0.13352476 0.         0.35606602 0.22254126]] 
[[0.184949269325230 0 0.493198051533946 0.308248782208716]
 [0.133524756441743 0 0.356066017177982 0.222541260736239]
 [0.133524756441743 0 0.356066017177982 0.222541260736239]
 [0.133524756441743 0 0.356066017177982 0.222541260736239]]


In [90]:
# import array_to_latex as a2l 

# Cycle graph $C^{4}$

In [91]:
C = nx.cycle_graph(4)
Anorm = normalize_adjacency(nx.adjacency_matrix(C))
Anorm.toarray()
# a2l.to_ltx(nx.adjacency_matrix(C).toarray(), frmt='{:.2f}', arraytype = 'bmatrix')
# a2l.to_ltx(Anorm.toarray(), frmt='{:.2f}', arraytype = 'bmatrix')

array([[0.33333333, 0.33333333, 0.        , 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.        ],
       [0.        , 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.        , 0.33333333, 0.33333333]])

In [92]:
A = Rational(1, 3) * Matrix([
    [1, 1, 0, 1],
    [1, 1, 1, 0],
    [0, 1, 1, 1],
    [1, 0, 1, 1]
])
Z_0_before_relu = A*X*W_0
Z_0 = Z_0_before_relu.applyfunc(lambda x: Max(0, x))
# print(latex(Z_0))
Z_0

Matrix([
[0.5, 0],
[0.5, 0],
[0.5, 0],
[0.5, 0]])

In [93]:
Z_1 = (A*Z_0*W_1).applyfunc(lambda x: Max(0, x))
# print(latex(Z_1))
Z_1

Matrix([
[0.15, 0, 0.4, 0.25],
[0.15, 0, 0.4, 0.25],
[0.15, 0, 0.4, 0.25],
[0.15, 0, 0.4, 0.25]])

### Numerical validation

In [94]:
X = np.ones((4, 1))
W0 = np.array([[0.5, -0.2]])
W1 = np.array([[0.3, -0.4, 0.8, 0.5], [-1.1, 0.6, -0.1, 0.7]])
Z0 = (Anorm@X@W0).clip(0, None)
Z1 = (Anorm@Z0@W1).clip(0, None)
Z0, Z1

(array([[0.5, 0. ],
        [0.5, 0. ],
        [0.5, 0. ],
        [0.5, 0. ]]),
 array([[0.15, 0.  , 0.4 , 0.25],
        [0.15, 0.  , 0.4 , 0.25],
        [0.15, 0.  , 0.4 , 0.25],
        [0.15, 0.  , 0.4 , 0.25]]))